### ISSUE TITLE
TypeScript Error

### ISSUE THREAD

**Issue by KageJittai** [bonzaiferroni/Traveler#3]
```
[at-loader] ./src/lib/Traveler.ts:704:17 
    TS2339: Property 'travelTo' does not exist on type 'Creep'. 

```

**Comment by bonzaiferroni** [comment]
I'm not aware of an easy way to make prototype additions play nice with the objects declared in screeps.d.ts. The way I do it is I made a file custom.d.ts and added something like this:

```
interface Creep {
    travelTo(destination: {pos: RoomPosition}|RoomPosition, ops?: any);
}
```

This consolidates with the interface declared in screeps.d.ts. and it is available everywhere without needing to import a type. The problem with this is that it requires some extra work and it can't be declared within Traveler.ts. It also means you are declaring options as `any` which means you don't get all the extra benefits of having a properly defined interface. I believe typings declarations cannot include imports or it changes their scope and they cease functioning as you'd expect typings declarations to function.

The way I get around this in my own code is I made a wrapper class for Creep. That seems to be the path of least resistance compared to adding things to the prototypes we get from the game API.

**Comment by KageJittai** [comment]
Maybe add the custom.d.ts to the repo so others can use the solution?  Anyone using TypeScript will need it.

**Comment by bonzaiferroni** [comment]
I think how people solve this problem will vary, some will use a wrapper class and may not want another declarations file. As it stands, the compiler error is useful as a reminder that you need to make sure to solve in some way.

If there is a convention for solving this issue that i'm not aware of I will definitely include it.

**Comment by ezolenko** [comment]
No reason not to publish .d.ts for traveler (move options interface in there as well to avoid `any` there).

**Comment by bonzaiferroni** [comment]
@ezolenko thank you, I went ahead and made a declarations file. I'm wondering if you have opinions on where I should put it in the repository, maybe `/libs/Traveler.d.ts`?

**Comment by bonzaiferroni** [comment]
I've added the new typings in this branch: https://github.com/bonzaiferroni/Traveler/tree/declarations

I'll merge if it looks good.

**Comment by kotarou** [comment]
Side note - you can add `/// <reference path='/path/to/index.d.ts' />` in files where you need to link the definitions, if you ever need to load the .js directly instead of using the ts module.

Typically I would put the .d.ts in the root of the dir, and name it as `index.d.ts`

**Comment by KageJittai** [comment]
Does travelTo have a return value?

**Comment by bonzaiferroni** [comment]
@kotarou  Thank you, .d.ts files are still a bit of a mystery to me. I've put it in the root folder, as you suggested. 
@KageJittai It does indeed, it returns the number values that `move` would return. I've updated the declaration file to reflect that.
