### ISSUE TITLE
traveler.js breaking char: `

### ISSUE THREAD

**Issue by kirkportas** [bonzaiferroni/Traveler#9]
The ` characters inside console.log statements break this file on Screeps as of July 23 '17.

**Comment by bonzaiferroni** [comment]
I wasn't able to reproduce this bug. For example, running this in the console did not thrown an exception:

```
console.log(`couldn't findRoute to destination`);
```

**Comment by kirkportas** [comment]
This was probably caused by copy pasting straight from Github into a file while on Windows, I'm not able to reproduce by other means or with similar lines of code. Closing this.
